### ISSUE TITLE
Teach MiniMaven to use the general Compiler API

### ISSUE THREAD

**Issue by ctrueden** [scijava/minimaven#9]
Similar to ImageJ 1.x' switch (made complicated by refusing to depend on Java6), switch to using javax.tools.Compiler:

https://github.com/fiji/ImageJA/commit/4982d01d85ba8f75317944275151ed557a0ebf28#L18R288

But let's use the ToolProvider interface as it was done here: https://github.com/scijava/scijava-common/commit/37f1fe9b7e6d500e7e41f65159eedb77fc03bd39
(but with a fallback if we're running in a JRE; we still might have Fiji's javac.jar in the class path).

That is just clarifying that MiniMaven does not depend on any GPLed library (even if the Java compiler shipped with Fiji is under GPL).

Migrated-From: http://trac.imagej.net/ticket/1658

**Comment by hinerm** [comment]
Tied to imagej/imagej/issues/105
